import { db, newsItemsTable, advisoriesTable, threatIntelTable } from "@workspace/db";

async function seed() {
  console.log("Seeding database...");

  await db.delete(threatIntelTable);
  await db.delete(newsItemsTable);
  await db.delete(advisoriesTable);

  const now = new Date();
  const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000);

  await db.insert(newsItemsTable).values([
    {
      title: "LockBit 4.0 Ransomware Campaign Targets Financial Sector",
      summary: "A new variant of LockBit ransomware has been observed targeting major financial institutions across North America and Europe.",
      content: "Security researchers have identified a new LockBit 4.0 variant that employs advanced evasion techniques including polymorphic code and living-off-the-land binaries. The campaign primarily targets financial sector organizations through spear-phishing emails containing malicious Excel macros. Initial access is gained through compromised VPN credentials purchased from dark web marketplaces. The ransomware encrypts files using AES-256 and demands payment in Monero cryptocurrency.",
      type: "news",
      scope: "global",
      severity: "critical",
      category: "Ransomware",
      source: "CrowdStrike Intelligence",
      sourceUrl: "https://crowdstrike.com/blog/lockbit-4",
      region: ["North America", "Europe"],
      tags: ["ransomware", "lockbit", "financial-sector", "apt"],
      iocs: ["185.220.101.45", "SHA256:a1b2c3d4e5f6", "evil-domain.com"],
      affectedSystems: ["Windows Server 2019", "Windows Server 2022"],
      mitigations: ["Update antivirus signatures", "Block known IOCs at firewall", "Enable MFA on VPN"],
      status: "active",
      publishedAt: hoursAgo(2),
      updatedAt: hoursAgo(1),
    },
    {
      title: "Critical Zero-Day in Apache Struts Exploited in the Wild",
      summary: "A critical remote code execution vulnerability in Apache Struts is being actively exploited by threat actors.",
      content: "Apache has disclosed CVE-2026-0001, a critical remote code execution vulnerability affecting Struts 2.x versions prior to 2.5.34. The vulnerability exists in the file upload mechanism and allows unauthenticated attackers to execute arbitrary code on affected servers. Exploitation has been observed in the wild, with multiple threat actors incorporating the exploit into their toolkits. Organizations running affected versions should patch immediately.",
      type: "news",
      scope: "global",
      severity: "critical",
      category: "Zero-Day",
      source: "US-CERT",
      sourceUrl: "https://us-cert.cisa.gov/ncas/alerts",
      region: ["Global"],
      tags: ["zero-day", "apache", "struts", "rce"],
      iocs: ["192.168.1.100", "exploit-kit.ru"],
      affectedSystems: ["Apache Struts 2.x < 2.5.34"],
      mitigations: ["Upgrade to Apache Struts 2.5.34", "Apply WAF rules", "Monitor for exploitation attempts"],
      status: "active",
      publishedAt: hoursAgo(4),
      updatedAt: hoursAgo(3),
    },
    {
      title: "Regional Phishing Campaign Targets Government Employees",
      summary: "A sophisticated phishing campaign is targeting government employees in the Southeast region with fake HR portals.",
      content: "A phishing campaign has been detected targeting government employees in the Southeast United States. The attackers use spoofed HR benefit portals that closely mimic legitimate government systems. Victims are lured through emails claiming urgent benefits enrollment deadlines. Stolen credentials are used to access internal government networks and exfiltrate sensitive documents. The campaign has been linked to a known APT group with ties to state-sponsored activities.",
      type: "news",
      scope: "local",
      severity: "high",
      category: "Phishing",
      source: "FBI Cyber Division",
      sourceUrl: "https://ic3.gov/alerts",
      region: ["Southeast US"],
      tags: ["phishing", "government", "credential-theft"],
      iocs: ["fake-hr-portal.com", "benefits-gov-update.net"],
      affectedSystems: ["Email Systems", "Web Browsers"],
      mitigations: ["Enable email filtering", "Train employees on phishing awareness", "Implement DMARC"],
      status: "active",
      publishedAt: hoursAgo(6),
      updatedAt: hoursAgo(5),
    },
    {
      title: "APT29 Targets Cloud Infrastructure with Novel Backdoor",
      summary: "Cozy Bear (APT29) has been observed deploying a new cloud-native backdoor targeting AWS and Azure environments.",
      content: "Microsoft Threat Intelligence has identified a new campaign by APT29 (Cozy Bear) targeting cloud infrastructure. The threat actor deploys a novel backdoor dubbed 'CloudNight' that abuses legitimate cloud service APIs to establish persistence and exfiltrate data. The backdoor communicates through Azure Storage queues and AWS SQS to evade network-based detection. Initial access is gained through compromised OAuth applications and stolen service principal credentials.",
      type: "news",
      scope: "global",
      severity: "high",
      category: "APT Activity",
      source: "Microsoft Threat Intelligence",
      sourceUrl: "https://microsoft.com/security/blog",
      region: ["Global"],
      tags: ["apt29", "cozy-bear", "cloud", "backdoor"],
      iocs: ["cloudnight-c2.azurewebsites.net", "malicious-oauth-app-id-12345"],
      affectedSystems: ["AWS", "Azure", "Microsoft 365"],
      mitigations: ["Audit OAuth app permissions", "Monitor cloud API calls", "Enable conditional access policies"],
      status: "active",
      publishedAt: hoursAgo(8),
      updatedAt: hoursAgo(7),
    },
    {
      title: "Major Data Breach at Healthcare Provider Exposes 2.5M Records",
      summary: "MedSecure Health Systems reports a data breach affecting 2.5 million patient records including PHI.",
      content: "MedSecure Health Systems has disclosed a significant data breach that exposed the personal health information (PHI) of approximately 2.5 million patients. The breach was discovered during a routine security audit and appears to have occurred over a three-month period. Compromised data includes names, Social Security numbers, medical records, insurance information, and billing data. The attack vector was a compromised third-party vendor with elevated network access.",
      type: "news",
      scope: "global",
      severity: "high",
      category: "Data Breach",
      source: "HHS Breach Portal",
      sourceUrl: "https://ocrportal.hhs.gov/ocr",
      region: ["North America"],
      tags: ["data-breach", "healthcare", "phi", "hipaa"],
      iocs: [],
      affectedSystems: ["Electronic Health Records", "Patient Portal"],
      mitigations: ["Credit monitoring for affected patients", "Vendor security assessment", "Network segmentation review"],
      status: "monitoring",
      publishedAt: hoursAgo(10),
      updatedAt: hoursAgo(9),
    },
    {
      title: "Local Power Grid SCADA Systems Targeted by Malware",
      summary: "A new malware strain targeting SCADA systems has been detected in regional power grid infrastructure.",
      content: "ICS-CERT has issued an alert regarding a new malware strain dubbed 'GridShock' that specifically targets SCADA systems used in regional power grid operations. The malware is capable of disrupting power distribution by manipulating programmable logic controllers (PLCs). Analysis shows the malware uses Modbus protocol manipulation to send malicious commands. Several regional utility companies have detected indicators of compromise in their operational technology networks.",
      type: "news",
      scope: "local",
      severity: "critical",
      category: "Infrastructure Threat",
      source: "ICS-CERT",
      sourceUrl: "https://ics-cert.us-cert.gov",
      region: ["Midwest US"],
      tags: ["scada", "ics", "power-grid", "critical-infrastructure"],
      iocs: ["gridshock-c2.onion", "SHA256:f7e8d9c0b1a2"],
      affectedSystems: ["Siemens S7-1200 PLC", "GE Mark VIe"],
      mitigations: ["Isolate OT networks", "Update PLC firmware", "Monitor Modbus traffic"],
      status: "active",
      publishedAt: hoursAgo(12),
      updatedAt: hoursAgo(11),
    },
    {
      title: "Emotet Botnet Returns with New Distribution Methods",
      summary: "The Emotet botnet has resurfaced with updated payload delivery mechanisms using OneNote attachments.",
      content: "After a brief disruption period, the Emotet botnet has resumed operations with significantly updated infection chains. The new campaign leverages Microsoft OneNote file attachments (.one) instead of the previously favored macro-enabled documents. These files contain embedded scripts that download and execute the Emotet loader. Once installed, Emotet serves as an initial access broker, deploying additional payloads including Cobalt Strike beacons and various ransomware families.",
      type: "news",
      scope: "global",
      severity: "medium",
      category: "Malware",
      source: "Proofpoint",
      sourceUrl: "https://proofpoint.com/threat-insight",
      region: ["Global"],
      tags: ["emotet", "botnet", "malware", "onenote"],
      iocs: ["emotet-loader.dll", "185.7.214.12", "download-update.top"],
      affectedSystems: ["Windows 10", "Windows 11", "Microsoft Office"],
      mitigations: ["Block OneNote attachments in email", "Update endpoint protection", "Enable ASR rules"],
      status: "active",
      publishedAt: hoursAgo(14),
      updatedAt: hoursAgo(13),
    },
    {
      title: "National CERT Issues Advisory on DNS Spoofing Attacks",
      summary: "Multiple DNS spoofing attacks targeting local ISPs have been reported by the national CERT team.",
      content: "The national CERT has issued an advisory warning of an increase in DNS spoofing attacks targeting local Internet Service Providers. The attackers are exploiting misconfigured recursive DNS resolvers to redirect users to malicious websites. Several local banking customers have reported being redirected to phishing sites that closely mimic their bank's online portal. ISPs are urged to implement DNSSEC validation and review their DNS infrastructure configurations.",
      type: "news",
      scope: "local",
      severity: "medium",
      category: "CERT Advisory",
      source: "National CERT",
      sourceUrl: "https://cert.gov/advisories",
      region: ["National"],
      tags: ["dns-spoofing", "isp", "cert", "phishing"],
      iocs: ["rogue-dns-1.malicious.com", "rogue-dns-2.malicious.com"],
      affectedSystems: ["BIND DNS", "Unbound DNS"],
      mitigations: ["Implement DNSSEC", "Audit DNS configurations", "Monitor DNS query logs"],
      status: "monitoring",
      publishedAt: hoursAgo(16),
      updatedAt: hoursAgo(15),
    },
    {
      title: "Supply Chain Attack on Popular NPM Package Affects Thousands",
      summary: "A popular NPM package with 4M weekly downloads was compromised, distributing malicious code to downstream projects.",
      content: "A supply chain attack targeting the popular NPM package 'event-stream-utils' has been discovered. The package maintainer's account was compromised through a credential stuffing attack, allowing the attacker to publish a malicious version. The compromised version includes a cryptocurrency miner and a credential stealer that targets environment variables. Over 4,000 downstream projects are estimated to be affected. The malicious version was live for approximately 48 hours before being detected and removed.",
      type: "news",
      scope: "global",
      severity: "high",
      category: "Supply Chain",
      source: "GitHub Security Advisory",
      sourceUrl: "https://github.com/advisories",
      region: ["Global"],
      tags: ["supply-chain", "npm", "javascript", "crypto-miner"],
      iocs: ["event-stream-utils@4.2.1", "mining-pool.malicious.com"],
      affectedSystems: ["Node.js applications", "CI/CD pipelines"],
      mitigations: ["Pin dependency versions", "Use npm audit", "Review dependency changes"],
      status: "resolved",
      publishedAt: hoursAgo(18),
      updatedAt: hoursAgo(17),
    },
    {
      title: "Compliance Update: New Data Protection Regulations",
      summary: "New regional data protection regulations take effect requiring enhanced security controls for data processors.",
      content: "New data protection regulations effective March 2026 introduce enhanced requirements for organizations processing personal data. Key changes include mandatory encryption for data at rest and in transit, 24-hour breach notification requirements, annual penetration testing mandates, and data processor audit rights. Organizations have a 90-day grace period to achieve compliance. Non-compliance penalties can reach up to 4% of annual revenue or $10 million, whichever is greater.",
      type: "news",
      scope: "local",
      severity: "info",
      category: "Compliance",
      source: "Data Protection Authority",
      sourceUrl: "https://dpa.gov/regulations",
      region: ["National"],
      tags: ["compliance", "data-protection", "regulation", "privacy"],
      iocs: [],
      affectedSystems: ["All data processing systems"],
      mitigations: ["Review data processing activities", "Implement encryption", "Update incident response plan"],
      status: "active",
      publishedAt: hoursAgo(20),
      updatedAt: hoursAgo(19),
    },
    {
      title: "Lazarus Group Launches New Cryptocurrency Exchange Attacks",
      summary: "North Korean APT group Lazarus is conducting a new campaign targeting cryptocurrency exchanges and DeFi platforms.",
      content: "Kaspersky researchers have uncovered a new campaign by the Lazarus Group targeting cryptocurrency exchanges and decentralized finance (DeFi) platforms. The attack uses trojanized trading applications and fake job offers on LinkedIn to gain initial access to target networks. Once inside, the attackers deploy custom malware to manipulate transaction systems and redirect funds to attacker-controlled wallets. Estimated losses from the campaign exceed $150 million across multiple exchanges.",
      type: "news",
      scope: "global",
      severity: "high",
      category: "APT Activity",
      source: "Kaspersky GReAT",
      sourceUrl: "https://securelist.com",
      region: ["Asia Pacific", "North America"],
      tags: ["lazarus", "north-korea", "cryptocurrency", "apt"],
      iocs: ["fake-trading-app.com", "linkedin-jobs-crypto.net"],
      affectedSystems: ["Trading platforms", "Crypto wallets"],
      mitigations: ["Verify application sources", "Multi-signature wallets", "Employee awareness training"],
      status: "active",
      publishedAt: hoursAgo(22),
      updatedAt: hoursAgo(21),
    },
    {
      title: "Vulnerability in Industrial IoT Sensors Allows Remote Takeover",
      summary: "Critical vulnerabilities in widely deployed IoT sensors allow unauthenticated remote code execution.",
      content: "Researchers at Claroty have discovered critical vulnerabilities in industrial IoT sensors manufactured by SensorTech Inc. The vulnerabilities affect the company's SmartSense line of environmental monitoring sensors used in manufacturing, energy, and water treatment facilities. An unauthenticated attacker can exploit the vulnerabilities to execute arbitrary code on the sensor, potentially manipulating readings or using the compromised device as a pivot point into the OT network. Over 50,000 affected devices are estimated to be deployed globally.",
      type: "news",
      scope: "global",
      severity: "medium",
      category: "IoT Vulnerability",
      source: "Claroty Research",
      sourceUrl: "https://claroty.com/research",
      region: ["Global"],
      tags: ["iot", "vulnerability", "industrial", "rce"],
      iocs: [],
      affectedSystems: ["SensorTech SmartSense v1.0-v3.2"],
      mitigations: ["Apply vendor patch", "Segment IoT networks", "Monitor for anomalous sensor behavior"],
      status: "monitoring",
      publishedAt: hoursAgo(24),
      updatedAt: hoursAgo(23),
    },
    {
      title: "State-Sponsored Disinformation Campaign Leverages Deepfakes",
      summary: "A coordinated disinformation campaign using AI-generated deepfake videos targets public infrastructure trust.",
      content: "Intelligence agencies have identified a state-sponsored disinformation campaign using AI-generated deepfake videos to undermine public trust in critical infrastructure. The campaign produces realistic videos of fake infrastructure failures, emergency alerts, and false government announcements. These are distributed through social media platforms and messaging apps. The campaign aims to create public panic and distrust in government institutions. AI analysis tools have identified distinctive artifacts in the deepfake videos that can be used for detection.",
      type: "news",
      scope: "local",
      severity: "medium",
      category: "Disinformation",
      source: "CISA",
      sourceUrl: "https://cisa.gov/news",
      region: ["National"],
      tags: ["disinformation", "deepfake", "ai", "state-sponsored"],
      iocs: [],
      affectedSystems: ["Social media platforms", "Messaging apps"],
      mitigations: ["Deploy deepfake detection tools", "Public awareness campaigns", "Media verification protocols"],
      status: "active",
      publishedAt: hoursAgo(26),
      updatedAt: hoursAgo(25),
    },
    {
      title: "Critical Fortinet FortiOS Authentication Bypass",
      summary: "A critical authentication bypass vulnerability in FortiOS allows remote attackers to gain super-admin access.",
      content: "Fortinet has disclosed a critical authentication bypass vulnerability (CVE-2026-0042) in FortiOS that allows remote unauthenticated attackers to gain super-admin privileges via crafted HTTP requests to the management interface. The vulnerability affects FortiOS versions 7.0.x through 7.4.x and is being actively exploited in the wild. Proof-of-concept exploit code has been published on multiple platforms. Organizations using affected Fortinet appliances should apply the emergency patch immediately.",
      type: "news",
      scope: "global",
      severity: "critical",
      category: "Vulnerability",
      source: "Fortinet PSIRT",
      sourceUrl: "https://fortiguard.com/psirt",
      region: ["Global"],
      tags: ["fortinet", "authentication-bypass", "cve", "firewall"],
      iocs: ["exploit-fortios.py", "185.56.83.200"],
      affectedSystems: ["FortiOS 7.0.x-7.4.x", "FortiGate Firewalls"],
      mitigations: ["Apply FortiOS patch", "Restrict management interface access", "Monitor for unauthorized admin sessions"],
      status: "active",
      publishedAt: hoursAgo(3),
      updatedAt: hoursAgo(2),
    },
    {
      title: "Ransomware Attack Disrupts Regional Hospital Network",
      summary: "A ransomware attack has disrupted operations at five hospitals in the regional healthcare network.",
      content: "The Regional Health Alliance, operating five hospitals and 23 clinics, has confirmed a ransomware attack that has disrupted electronic health records, medical device connectivity, and administrative systems. The BlackCat (ALPHV) ransomware group has claimed responsibility, demanding $5 million in cryptocurrency. Emergency services have been diverted to unaffected facilities. The FBI and CISA are providing technical assistance. Patient care is being maintained through manual processes and paper records.",
      type: "news",
      scope: "local",
      severity: "critical",
      category: "Ransomware",
      source: "Local News / FBI",
      sourceUrl: "https://fbi.gov/news",
      region: ["Northeast US"],
      tags: ["ransomware", "healthcare", "blackcat", "alphv"],
      iocs: ["blackcat-onion-site.onion"],
      affectedSystems: ["Epic EHR", "Medical devices", "PACS systems"],
      mitigations: ["Activate incident response plan", "Engage forensics team", "Restore from backups"],
      status: "active",
      publishedAt: hoursAgo(1),
      updatedAt: hoursAgo(0.5),
    },
  ]);

  await db.insert(advisoriesTable).values([
    {
      cveId: "CVE-2026-0001",
      title: "Apache Struts Remote Code Execution",
      description: "A critical remote code execution vulnerability in Apache Struts 2.x allows unauthenticated attackers to execute arbitrary code on the server through crafted file upload requests. The vulnerability exists due to improper input validation in the file upload mechanism.",
      cvssScore: 9.8,
      severity: "critical",
      affectedProducts: ["Apache Struts 2.0.0 - 2.5.33"],
      vendor: "Apache",
      patchAvailable: true,
      patchUrl: "https://struts.apache.org/releases",
      workarounds: ["Disable file upload functionality", "Apply WAF rules to block exploit patterns"],
      references: ["https://nvd.nist.gov/vuln/detail/CVE-2026-0001", "https://struts.apache.org/security"],
      status: "new",
      publishedAt: hoursAgo(4),
    },
    {
      cveId: "CVE-2026-0042",
      title: "Fortinet FortiOS Authentication Bypass",
      description: "A critical authentication bypass vulnerability in FortiOS allows remote unauthenticated attackers to gain super-admin privileges via crafted HTTP requests to the administrative interface. Active exploitation has been confirmed in the wild.",
      cvssScore: 9.6,
      severity: "critical",
      affectedProducts: ["FortiOS 7.0.0-7.0.14", "FortiOS 7.2.0-7.2.7", "FortiOS 7.4.0-7.4.3"],
      vendor: "Fortinet",
      patchAvailable: true,
      patchUrl: "https://fortiguard.com/psirt/FG-IR-24-015",
      workarounds: ["Restrict management interface to trusted IPs", "Disable HTTP/HTTPS admin access"],
      references: ["https://nvd.nist.gov/vuln/detail/CVE-2026-0042", "https://fortiguard.com/psirt"],
      status: "new",
      publishedAt: hoursAgo(3),
    },
    {
      cveId: "CVE-2026-1234",
      title: "Microsoft Exchange Server Elevation of Privilege",
      description: "An elevation of privilege vulnerability in Microsoft Exchange Server allows authenticated attackers to escalate to SYSTEM privileges. The vulnerability exists in the Exchange PowerShell backend and can be exploited through specially crafted requests.",
      cvssScore: 8.1,
      severity: "high",
      affectedProducts: ["Exchange Server 2019 CU13", "Exchange Server 2016 CU23"],
      vendor: "Microsoft",
      patchAvailable: true,
      patchUrl: "https://msrc.microsoft.com/update-guide",
      workarounds: ["Disable PowerShell remoting for non-admin users", "Apply least privilege principles"],
      references: ["https://nvd.nist.gov/vuln/detail/CVE-2026-1234", "https://msrc.microsoft.com"],
      status: "under_review",
      publishedAt: hoursAgo(48),
    },
    {
      cveId: "CVE-2026-2345",
      title: "Linux Kernel Privilege Escalation via io_uring",
      description: "A use-after-free vulnerability in the Linux kernel's io_uring subsystem allows local attackers to escalate privileges to root. The vulnerability affects kernels 5.10 through 6.7 and can be exploited by unprivileged users.",
      cvssScore: 7.8,
      severity: "high",
      affectedProducts: ["Linux Kernel 5.10-6.7"],
      vendor: "Linux",
      patchAvailable: true,
      patchUrl: "https://kernel.org/pub/linux/kernel",
      workarounds: ["Disable io_uring for unprivileged users: sysctl -w kernel.io_uring_disabled=2"],
      references: ["https://nvd.nist.gov/vuln/detail/CVE-2026-2345"],
      status: "patched",
      publishedAt: hoursAgo(72),
    },
    {
      cveId: "CVE-2026-3456",
      title: "VMware vCenter Server SSRF Vulnerability",
      description: "A server-side request forgery (SSRF) vulnerability in VMware vCenter Server allows attackers with network access to make requests to internal services. This can lead to information disclosure and potentially enable further attacks on internal infrastructure.",
      cvssScore: 6.5,
      severity: "medium",
      affectedProducts: ["vCenter Server 8.0 U2", "vCenter Server 7.0 U3"],
      vendor: "VMware",
      patchAvailable: false,
      workarounds: ["Restrict network access to vCenter Server", "Monitor for unusual outbound connections"],
      references: ["https://vmware.com/security/advisories"],
      status: "under_review",
      publishedAt: hoursAgo(96),
    },
    {
      cveId: "CVE-2026-4567",
      title: "Cisco IOS XE Web UI Information Disclosure",
      description: "An information disclosure vulnerability in Cisco IOS XE Software Web UI allows unauthenticated remote attackers to access sensitive configuration data including SNMP community strings and local user credentials.",
      cvssScore: 5.3,
      severity: "medium",
      affectedProducts: ["Cisco IOS XE 17.9.x", "Cisco IOS XE 17.10.x"],
      vendor: "Cisco",
      patchAvailable: true,
      patchUrl: "https://tools.cisco.com/security/center",
      workarounds: ["Disable web UI", "Restrict access to management interface"],
      references: ["https://tools.cisco.com/security/center"],
      status: "patched",
      publishedAt: hoursAgo(120),
    },
    {
      cveId: "CVE-2026-5678",
      title: "WordPress Plugin Cross-Site Scripting",
      description: "A stored cross-site scripting (XSS) vulnerability in the popular WordPress Contact Form plugin (installed on over 5 million sites) allows authenticated users with contributor role to inject malicious scripts.",
      cvssScore: 4.3,
      severity: "low",
      affectedProducts: ["WP Contact Form Pro < 5.1.2"],
      vendor: "WordPress",
      patchAvailable: true,
      patchUrl: "https://wordpress.org/plugins/contact-form-pro",
      workarounds: ["Restrict contributor role permissions", "Install WAF plugin"],
      references: ["https://wpscan.com/vulnerability/12345"],
      status: "patched",
      publishedAt: hoursAgo(144),
    },
  ]);

  await db.insert(threatIntelTable).values([
    {
      title: "LockBit 4.0 Ransomware Campaign",
      summary: "Advanced ransomware campaign targeting financial institutions with polymorphic LockBit 4.0 variant.",
      description: "Security researchers have identified a new LockBit 4.0 variant that employs advanced evasion techniques including polymorphic code and living-off-the-land binaries. The campaign primarily targets financial sector organizations through spear-phishing emails containing malicious Excel macros. Initial access is gained through compromised VPN credentials purchased from dark web marketplaces.",
      scope: "global",
      severity: "critical",
      category: "Ransomware",
      threatActor: "LockBit Gang",
      threatActorAliases: ["ABCD", "Gold Mystic"],
      targetSectors: ["Financial Services", "Banking", "Insurance"],
      targetRegions: ["North America", "Europe"],
      ttps: ["T1566.001 - Spear Phishing Attachment", "T1059.001 - PowerShell", "T1486 - Data Encrypted for Impact", "T1078 - Valid Accounts"],
      iocs: ["185.220.101.45", "SHA256:a1b2c3d4e5f6", "evil-domain.com", "lockbit-c2.onion"],
      malwareFamilies: ["LockBit 4.0", "Cobalt Strike"],
      affectedSystems: ["Windows Server 2019", "Windows Server 2022"],
      mitigations: ["Update antivirus signatures", "Block known IOCs at firewall", "Enable MFA on VPN", "Disable macro execution"],
      source: "CrowdStrike Intelligence",
      sourceUrl: "https://crowdstrike.com/blog/lockbit-4",
      references: ["https://attack.mitre.org/groups/G0106"],
      campaignName: "Operation Dark Vault",
      status: "active",
      confidenceLevel: "confirmed",
      firstSeen: hoursAgo(168),
      lastSeen: hoursAgo(2),
      publishedAt: hoursAgo(2),
      updatedAt: hoursAgo(1),
    },
    {
      title: "APT29 CloudNight Backdoor Campaign",
      summary: "Cozy Bear deploys novel cloud-native backdoor targeting AWS and Azure infrastructure.",
      description: "Microsoft Threat Intelligence has identified a new campaign by APT29 (Cozy Bear) targeting cloud infrastructure. The threat actor deploys a novel backdoor dubbed 'CloudNight' that abuses legitimate cloud service APIs to establish persistence and exfiltrate data. The backdoor communicates through Azure Storage queues and AWS SQS to evade network-based detection.",
      scope: "global",
      severity: "high",
      category: "APT Activity",
      threatActor: "APT29",
      threatActorAliases: ["Cozy Bear", "The Dukes", "NOBELIUM"],
      targetSectors: ["Government", "Technology", "Defense"],
      targetRegions: ["North America", "Europe", "Asia Pacific"],
      ttps: ["T1078.004 - Cloud Accounts", "T1567.002 - Exfiltration to Cloud Storage", "T1550.001 - Application Access Token", "T1098 - Account Manipulation"],
      iocs: ["cloudnight-c2.azurewebsites.net", "malicious-oauth-app-id-12345", "SHA256:e9f0a1b2c3d4e5f6"],
      malwareFamilies: ["CloudNight", "MagicWeb"],
      affectedSystems: ["AWS", "Azure", "Microsoft 365"],
      mitigations: ["Audit OAuth app permissions", "Monitor cloud API calls", "Enable conditional access policies"],
      source: "Microsoft Threat Intelligence",
      sourceUrl: "https://microsoft.com/security/blog",
      references: ["https://attack.mitre.org/groups/G0016"],
      campaignName: "CloudNight",
      status: "active",
      confidenceLevel: "high",
      firstSeen: hoursAgo(720),
      lastSeen: hoursAgo(8),
      publishedAt: hoursAgo(8),
      updatedAt: hoursAgo(7),
    },
    {
      title: "GridShock ICS/SCADA Malware",
      summary: "New malware strain targeting SCADA systems in regional power grid infrastructure.",
      description: "ICS-CERT has issued an alert regarding a new malware strain dubbed 'GridShock' that specifically targets SCADA systems used in regional power grid operations. The malware is capable of disrupting power distribution by manipulating programmable logic controllers (PLCs). Analysis shows the malware uses Modbus protocol manipulation to send malicious commands.",
      scope: "local",
      severity: "critical",
      category: "ICS/OT Threat",
      threatActor: "Sandworm",
      threatActorAliases: ["Voodoo Bear", "IRIDIUM"],
      targetSectors: ["Energy", "Utilities", "Critical Infrastructure"],
      targetRegions: ["Midwest US", "Eastern Europe"],
      ttps: ["T0855 - Unauthorized Command Message", "T0831 - Manipulation of Control", "T0836 - Modify Parameter"],
      iocs: ["gridshock-c2.onion", "SHA256:f7e8d9c0b1a2", "192.168.100.50"],
      malwareFamilies: ["GridShock", "Industroyer2"],
      affectedSystems: ["Siemens S7-1200 PLC", "GE Mark VIe", "ABB RTU560"],
      mitigations: ["Isolate OT networks", "Update PLC firmware", "Monitor Modbus traffic", "Deploy industrial IDS"],
      source: "ICS-CERT",
      sourceUrl: "https://ics-cert.us-cert.gov",
      references: ["https://attack.mitre.org/groups/G0034"],
      campaignName: "Operation GridShock",
      status: "active",
      confidenceLevel: "confirmed",
      firstSeen: hoursAgo(336),
      lastSeen: hoursAgo(12),
      publishedAt: hoursAgo(12),
      updatedAt: hoursAgo(11),
    },
    {
      title: "Lazarus Cryptocurrency Exchange Campaign",
      summary: "North Korean APT group Lazarus targeting cryptocurrency exchanges and DeFi platforms.",
      description: "Kaspersky researchers have uncovered a new campaign by the Lazarus Group targeting cryptocurrency exchanges and DeFi platforms. The attack uses trojanized trading applications and fake job offers on LinkedIn. Once inside, attackers deploy custom malware to manipulate transaction systems. Estimated losses exceed $150 million.",
      scope: "global",
      severity: "high",
      category: "Financial Threat",
      threatActor: "Lazarus Group",
      threatActorAliases: ["Hidden Cobra", "APT38", "Zinc"],
      targetSectors: ["Cryptocurrency", "Financial Services", "DeFi"],
      targetRegions: ["Asia Pacific", "North America", "Europe"],
      ttps: ["T1566.003 - Spearphishing via Service", "T1204.002 - Malicious File", "T1055 - Process Injection", "T1565.001 - Stored Data Manipulation"],
      iocs: ["fake-trading-app.com", "linkedin-jobs-crypto.net", "SHA256:abc123def456"],
      malwareFamilies: ["TraderTraitor", "AppleJeus"],
      affectedSystems: ["Trading platforms", "Crypto wallets", "macOS", "Windows"],
      mitigations: ["Verify application sources", "Multi-signature wallets", "Employee awareness training"],
      source: "Kaspersky GReAT",
      sourceUrl: "https://securelist.com",
      references: ["https://attack.mitre.org/groups/G0032"],
      campaignName: "Operation CryptoHeist",
      status: "active",
      confidenceLevel: "high",
      firstSeen: hoursAgo(480),
      lastSeen: hoursAgo(22),
      publishedAt: hoursAgo(22),
      updatedAt: hoursAgo(21),
    },
    {
      title: "Emotet Botnet Resurgence via OneNote",
      summary: "Emotet botnet returns with new distribution via OneNote attachments and updated C2 infrastructure.",
      description: "After a brief disruption period, the Emotet botnet has resumed operations with significantly updated infection chains. The new campaign leverages Microsoft OneNote file attachments (.one) instead of the previously favored macro-enabled documents. Once installed, Emotet serves as an initial access broker, deploying additional payloads including Cobalt Strike beacons.",
      scope: "global",
      severity: "medium",
      category: "Malware",
      threatActor: "Mealybug",
      threatActorAliases: ["TA542", "Mummy Spider"],
      targetSectors: ["All Sectors"],
      targetRegions: ["Global"],
      ttps: ["T1566.001 - Spear Phishing Attachment", "T1059.005 - Visual Basic", "T1547.001 - Registry Run Keys"],
      iocs: ["emotet-loader.dll", "185.7.214.12", "download-update.top"],
      malwareFamilies: ["Emotet", "Cobalt Strike", "QakBot"],
      affectedSystems: ["Windows 10", "Windows 11", "Microsoft Office"],
      mitigations: ["Block OneNote attachments in email", "Update endpoint protection", "Enable ASR rules"],
      source: "Proofpoint",
      sourceUrl: "https://proofpoint.com/threat-insight",
      references: ["https://attack.mitre.org/software/S0367"],
      status: "active",
      confidenceLevel: "confirmed",
      firstSeen: hoursAgo(240),
      lastSeen: hoursAgo(14),
      publishedAt: hoursAgo(14),
      updatedAt: hoursAgo(13),
    },
    {
      title: "FortiOS Authentication Bypass Exploitation",
      summary: "Active exploitation of critical FortiOS authentication bypass allowing super-admin access.",
      description: "Active exploitation campaign targeting CVE-2026-0042, a critical authentication bypass in FortiOS. Attackers gain super-admin privileges via crafted HTTP requests to the management interface. PoC exploit code published on multiple platforms. Multiple threat actors are scanning for and exploiting vulnerable instances.",
      scope: "global",
      severity: "critical",
      category: "Vulnerability Exploitation",
      threatActor: "Multiple Actors",
      threatActorAliases: [],
      targetSectors: ["All Sectors"],
      targetRegions: ["Global"],
      ttps: ["T1190 - Exploit Public-Facing Application", "T1078 - Valid Accounts", "T1136 - Create Account"],
      iocs: ["exploit-fortios.py", "185.56.83.200", "45.129.14.100"],
      malwareFamilies: [],
      affectedSystems: ["FortiOS 7.0.x-7.4.x", "FortiGate Firewalls"],
      mitigations: ["Apply FortiOS patch", "Restrict management interface access", "Monitor for unauthorized admin sessions"],
      source: "Fortinet PSIRT",
      sourceUrl: "https://fortiguard.com/psirt",
      references: ["https://nvd.nist.gov/vuln/detail/CVE-2026-0042"],
      status: "active",
      confidenceLevel: "confirmed",
      firstSeen: hoursAgo(72),
      lastSeen: hoursAgo(3),
      publishedAt: hoursAgo(3),
      updatedAt: hoursAgo(2),
    },
    {
      title: "Regional Government Phishing Campaign",
      summary: "Sophisticated phishing targeting government employees with fake HR benefit portals.",
      description: "A phishing campaign has been detected targeting government employees in the Southeast United States. The attackers use spoofed HR benefit portals that closely mimic legitimate government systems. Victims are lured through emails claiming urgent benefits enrollment deadlines. Stolen credentials are used to access internal networks.",
      scope: "local",
      severity: "high",
      category: "Phishing Campaign",
      threatActor: "Unknown",
      threatActorAliases: [],
      targetSectors: ["Government", "Public Sector"],
      targetRegions: ["Southeast US"],
      ttps: ["T1566.002 - Spearphishing Link", "T1078 - Valid Accounts", "T1114 - Email Collection"],
      iocs: ["fake-hr-portal.com", "benefits-gov-update.net", "192.168.50.25"],
      malwareFamilies: [],
      affectedSystems: ["Email Systems", "Web Browsers", "VPN"],
      mitigations: ["Enable email filtering", "Train employees on phishing awareness", "Implement DMARC"],
      source: "FBI Cyber Division",
      sourceUrl: "https://ic3.gov/alerts",
      references: [],
      status: "active",
      confidenceLevel: "high",
      firstSeen: hoursAgo(120),
      lastSeen: hoursAgo(6),
      publishedAt: hoursAgo(6),
      updatedAt: hoursAgo(5),
    },
    {
      title: "IoT Sensor Vulnerabilities in Industrial Settings",
      summary: "Critical vulnerabilities in industrial IoT sensors allow unauthenticated remote code execution.",
      description: "Researchers at Claroty have discovered critical vulnerabilities in industrial IoT sensors manufactured by SensorTech Inc. The vulnerabilities affect the SmartSense line used in manufacturing, energy, and water treatment. An unauthenticated attacker can execute arbitrary code, potentially manipulating readings or pivoting into OT networks. Over 50,000 affected devices deployed globally.",
      scope: "global",
      severity: "medium",
      category: "IoT Vulnerability",
      threatActor: "Unknown",
      threatActorAliases: [],
      targetSectors: ["Manufacturing", "Energy", "Water Treatment"],
      targetRegions: ["Global"],
      ttps: ["T0866 - Exploitation of Remote Services", "T0882 - Theft of Operational Information"],
      iocs: [],
      malwareFamilies: [],
      affectedSystems: ["SensorTech SmartSense v1.0-v3.2"],
      mitigations: ["Apply vendor patch", "Segment IoT networks", "Monitor for anomalous sensor behavior"],
      source: "Claroty Research",
      sourceUrl: "https://claroty.com/research",
      references: ["https://claroty.com/team82/research"],
      status: "monitoring",
      confidenceLevel: "medium",
      firstSeen: hoursAgo(168),
      lastSeen: hoursAgo(24),
      publishedAt: hoursAgo(24),
      updatedAt: hoursAgo(23),
    },
    {
      title: "Apache Struts Zero-Day Active Exploitation",
      summary: "Critical RCE zero-day in Apache Struts being exploited by multiple threat actors.",
      description: "CVE-2026-0001, a critical remote code execution vulnerability in Apache Struts 2.x, is being actively exploited in the wild. The vulnerability exists in the file upload mechanism and allows unauthenticated attackers to execute arbitrary code. Multiple threat actors have incorporated the exploit into their toolkits.",
      scope: "global",
      severity: "critical",
      category: "Zero-Day",
      threatActor: "Multiple Actors",
      threatActorAliases: [],
      targetSectors: ["Technology", "Financial Services", "Government"],
      targetRegions: ["Global"],
      ttps: ["T1190 - Exploit Public-Facing Application", "T1059 - Command and Scripting Interpreter"],
      iocs: ["192.168.1.100", "exploit-kit.ru", "struts-exploit.sh"],
      malwareFamilies: ["Various webshells"],
      affectedSystems: ["Apache Struts 2.x < 2.5.34"],
      mitigations: ["Upgrade to Apache Struts 2.5.34", "Apply WAF rules", "Monitor for exploitation attempts"],
      source: "US-CERT",
      sourceUrl: "https://us-cert.cisa.gov/ncas/alerts",
      references: ["https://nvd.nist.gov/vuln/detail/CVE-2026-0001"],
      campaignName: "Struts Storm",
      status: "active",
      confidenceLevel: "confirmed",
      firstSeen: hoursAgo(96),
      lastSeen: hoursAgo(4),
      publishedAt: hoursAgo(4),
      updatedAt: hoursAgo(3),
    },
  ]);

  console.log("Seed data inserted successfully!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
